app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/',         ['as' => 'home',            'uses' => 'HomeController@index']);
Route::get('login',     ['as' => 'login',           'uses' => 'LoginController@index']);
Route::post('login',    ['as' => 'login.submit',    'uses' => 'LoginController@submit']);
Route::get('logout',    ['as' => 'logout',          'uses' => 'LoginController@logout']);

Route::get('scan.php', 'DownloadController@getScan');
Route::controller('register', 'RegisterController');
Route::controller('panduan', 'PanduanController');
Route::controller('instruksi-kerja', 'InstruksiKerjaController');

Route::group(['namespace' => 'Backend', 'prefix' => 'backend', 'middleware' => ['auth', 'admin']], function()
{
    Route::get('/',                                         ['as' => 'backend',                             'uses' => 'HomeController@index']);
    Route::get('permintaan/active',                         ['as' => 'backend.permintaan.active',           'uses' => 'PermintaanController@active']);
    Route::get('permintaan/suspend',                        ['as' => 'backend.permintaan.showsuspend',      'uses' => 'PermintaanController@showSuspend']);
    Route::get('permintaan/{id}/activation',                ['as' => 'backend.permintaan.proccess',         'uses' => 'PermintaanController@proccess']);
    Route::get('permintaan/{id}/sendmail-activation',       ['as' => 'backend.permintaan.active.sendmail',  'uses' => 'PermintaanController@sendMailActivation']);
    Route::get('permintaan/{id}/destroy',                   ['as' => 'backend.permintaan.destroy.confirm',  'uses' => 'PermintaanController@destroyConfirm']);
    Route::get('permintaan/{id}/suspend',                   ['as' => 'backend.permintaan.suspend',          'uses' => 'PermintaanController@suspend']);
    Route::get('permintaan/{id}/unsuspend',                 ['as' => 'backend.permintaan.unsuspend',        'uses' => 'PermintaanController@unsuspend']);

    Route::resource('permintaan',                           'PermintaanController');

    Route::get('user/password/{id}',                        ['as' => 'backend.user.password',               'uses' => 'UserController@password']);
    Route::post('user/password/{id}',                       ['as' => 'backend.user.password.submit',        'uses' => 'UserController@change']);
    Route::resource('user', 'UserController');

    Route::get('upload',                                    ['as' => 'backend.upload.form',                 'uses' => 'UploadController@form']);
    Route::post('upload',                                   ['as' => 'backend.upload.submit',               'uses' => 'UploadController@submit']);

    Route::controller('laporan', 'LaporanController', [
        'getIndex'      => 'backend.laporan.index',
        'postDownload'  => 'backend.laporan.download',
    ]);

});

Route::group(['middleware' => 'auth.mahasiswa', 'namespace' => 'Mahasiswa'], function()
{
    Route::get('download/{dir?}',       ['as' => 'jurnal.show',     'uses' => 'JurnalController@show'])->where('dir', '([A-Za-z]+/?)+');
    Route::get('download-get/{dir?}',   ['as' => 'jurnal.download', 'uses' => 'JurnalController@download']);
});

Route::group(['prefix' => 'mahasiswa', 'namespace' => 'Mahasiswa'], function()
{
    Route::get('login',     ['as' => 'mahasiswa.login',           'uses' => 'LoginController@index']);
    Route::post('login',    ['as' => 'mahasiswa.login.submit',    'uses' => 'LoginController@submit']);

    Route::group(['middleware' => 'auth.mahasiswa'], function()
    {
        Route::get('logout',                ['as' => 'mahasiswa.logout',    'uses' => 'LoginController@logout']);
        Route::get('profile',               ['as' => 'mahasiswa.edit',      'uses' => 'UserController@edit']);
        Route::put('profile',               ['as' => 'mahasiswa.update',    'uses' => 'UserController@update']);
        Route::get('profile/password',      ['as' => 'mahasiswa.password',  'uses' => 'UserController@password']);
        Route::post('profile/password',     ['as' => 'mahasiswa.change',    'uses' => 'UserController@change']);
        Route::get('doc/{nim}',             ['as' => 'mahasiswa.doc',       'uses' => 'DocumentController@show']);
        Route::get('doc/{nim}/{filename}',  ['as' => 'mahasiswa.doc.pdf',   'uses' => 'DocumentController@pdf']);
    });
});


// Validator Extends

Validator::extend('kapasitas', function($attribute, $value, $parameters)
{
    return $value <= 50;
});

Validator::extend('old', function($attribute, $value, $parameters)
{
    $id     = $parameters[0];
    $user   = App\User::find($id);

    return Hash::check($value, $user->password);
});


Route::get('tesmail', function()
{
    $data['mahasiswa'] = App\Mahasiswa::first();

    Mail::send('emails.basic', $data, function($message)
    {
        $message->to('nurmanhabib@gmail.com', 'Habib Nurrahman')->subject('Coba Kirim Email');
    });
});

Route::get('quota', function()
{
    // $quota = new Nurmanhabib\QuotaTool\QuotaTool('/');
    // $quota->uid('habib');
    // $quota->limit(100024, 2000000);
    QuotaTool::filesystem('/');
    QuotaTool::uid('nurmanhabib')->limit('50G', '51G');

    echo QuotaTool::raw();

    echo '<hr>';

    echo QuotaTool::getLimit();
});

resources/views/layout/backend.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{!! $page_title or "Dashboard" !!} - {!! $site_title or "Control Panel Skripsi TIF UAD" !!}</title>

    @section('style')
    <!-- Bootstrap Core CSS -->
    {!! HTML::style('bower_components/bootstrap/dist/css/bootstrap.min.css') !!}

    <!-- MetisMenu CSS -->
    {!! HTML::style('bower_components/metisMenu/dist/metisMenu.min.css') !!}

    <!-- Custom CSS -->
    {!! HTML::style('dist/css/sb-admin-2.css') !!}

    <!-- Custom Fonts -->
    {!! HTML::style('bower_components/font-awesome/css/font-awesome.min.css') !!}

    {!! HTML::style('css/daterangepicker-bs3.css') !!}

    {!! HTML::style('css/skriptif.css') !!}
    @show

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{!! route('backend') !!}">{!! $site_title or "Control Panel Skripsi TIF UAD" !!}</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{!! route('backend.user.edit', $my->id) !!}"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{!! route('logout') !!}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">

                    {!! Navigator::show() !!}

                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">{!! $page_title or "Dashboard" !!}</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->

                <div class="row">
                    @include('errors.session')
                </div>

                @section('content')
                    <p>No content here.</p>
                @show
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    @section('script')
    <!-- jQuery -->
    {!! HTML::script('bower_components/jquery/dist/jquery.min.js') !!}

    <!-- Bootstrap Core JavaScript -->
    {!! HTML::script('bower_components/bootstrap/dist/js/bootstrap.min.js') !!}

    <!-- Metis Menu Plugin JavaScript -->
    {!! HTML::script('bower_components/metisMenu/dist/metisMenu.min.js') !!}

    <!-- Custom Theme JavaScript -->
    {!! HTML::script('dist/js/sb-admin-2.js') !!}
    
    {!! HTML::script('js/moment.min.js') !!}
    {!! HTML::script('js/daterangepicker.js') !!}

    <!-- Custom Web JavaScript -->
    {!! HTML::script('js/skriptif.js') !!}
    @show

</body>

</html>

resources/views/layout/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{!! $page_title or "Dashboard" !!} - {!! $site_title or "Control Panel Skripsi TIF UAD" !!}</title>

    @section('style')
    <!-- Bootstrap Core CSS -->
    {!! HTML::style('bower_components/bootstrap/dist/css/bootstrap.min.css') !!}

    <!-- MetisMenu CSS -->
    {!! HTML::style('bower_components/metisMenu/dist/metisMenu.min.css') !!}

    <!-- Custom CSS -->
    {!! HTML::style('dist/css/sb-admin-2.css') !!}

    <!-- Custom Fonts -->
    {!! HTML::style('bower_components/font-awesome/css/font-awesome.min.css') !!}
    @show

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        @include('errors.session')

                        {!! Form::open(['route' => 'login.submit']) !!}
                            <fieldset>
                                <div class="form-group">
                                    {!! Form::text('username', null, ['class' => 'form-control', 'placeholder' => 'Username']) !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password']) !!}
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                {!! Form::submit('Login', ['class' => 'btn btn-lg btn-success btn-block']) !!}
                            </fieldset>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

    @section('script')
    <!-- jQuery -->
    {!! HTML::script('bower_components/jquery/dist/jquery.min.js') !!}

    <!-- Bootstrap Core JavaScript -->
    {!! HTML::script('bower_components/bootstrap/dist/js/bootstrap.min.js') !!}

    <!-- Metis Menu Plugin JavaScript -->
    {!! HTML::script('bower_components/metisMenu/dist/metisMenu.min.js') !!}

    <!-- Custom Theme JavaScript -->
    {!! HTML::script('dist/js/sb-admin-2.js') !!}
    @show

</body>

</html>

resources/views/layout/portal.blade.php
<html>
<head>
    <meta charset="UTF-8">
    <title>Portal Skripsi Teknik Informatika</title>

    <!-- Untuk CSS -->
    @section('style')
    {!! HTML::style('css/bootstrap.css') !!}
    {!! HTML::style('css/stylesheet.css') !!}
    {!! HTML::style('css/font-awesome.css') !!}
    {!! HTML::style('css/font.css') !!}
    {!! HTML::style('css/style.css') !!}
    {!! HTML::style('http://fonts.googleapis.com/css?family=Lato:400,700') !!}
    @show

</head>

<body id="offcanvas-container" class="offcanvas-container fs12 page-home " data-twttr-rendered="true">

    <!--header-->
    <section id="header">

        <!--topbar-->
        <section id="topbar">
        </section>
        <!--end top bar-->


        <!--Header Main-->
        <section id="header-main">
            <div class="container">
                <div class="row header-wrap">
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 inner">
                        <div class="logo">
                            <a href="{!! url('/') !!}">
                                <img src="{!! asset('img/logo.png') !!}" class="img-responsive">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--End Header-->

        <!--Navbar-->
        <section id="pav-mainnav">
            <div class="container">
                <nav class="navbar navbar-default" role="navigation">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li>{!! link_to('/', 'Home') !!}</li>
                            <li>{!! link_to('download', 'Download') !!}</li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Register <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>{!! link_to('register/jurnal', 'Register Jurnal') !!}</li>
                                    <li>{!! link_to('register', 'Register Hosting') !!}</li>
                                </ul>
                            </li>
                            <li>{!! link_to('panduan', 'Panduan') !!}</li>
                            <li>{!! link_to('instruksi-kerja', 'Instruksi Kerja (IK)') !!}</li>
                        </ul>
                     
                        <ul class="nav navbar-nav navbar-right">
                            @if(Auth::guest())
                            <li>{!! link_to(route('mahasiswa.login'), 'Login') !!}</li>
                            @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Akun <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>{!! link_to(route('mahasiswa.edit'), 'Profile [' . Auth::user()->name . ']') !!}</li>
                                    <li>{!! link_to(route('mahasiswa.logout'), 'Logout') !!}</li>
                                </ul>
                            </li>
                            @endif
                            <form action="{!! route('home') !!}" class="navbar-form navbar-left" role="search">
                                <div class="form-group">
                                    {!! Form::text('cari', Input::get('cari'), ['class' => 'form-control', 'placeholder' => 'Search']) !!}
                                </div>
                                <button type="submit" class="btn btn-default fa fa-search"></button>
                            </form>
                        </ul>
                    </div> <!-- /.navbar-collapse -->
                </nav>
            </div>
        </section> <!--End Navbar-->
    </section> <!--End Header-->
    
    <section id="columns" class="offcanvas-siderbars">
        <div class="container">
            <div class="row">
            
                <section class="col-lg-12 col-md-12 col-sm-12 col-xs-12 main-column">         
                    <div id="content">

                        <!--Slider-->   
                        <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img alt="900x500" src="{!! asset('img/url.png') !!}">          
                                </div>
                                <div class="item">
                                    <img alt="900x500" src="{!! asset('img/slide1.png') !!}">          
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-captions" data-slide="prev"></a>
                            <a class="right carousel-control" href="#carousel-example-captions" data-slide="next"></a>
                        </div>
                        <!--End Slider-->

                        <!--Artikel-->
                        <div class="container">
                            <div class="page-header">
                                <h1><i class="fa fa-desktop fa-fw"></i> {!! $page_title or "Default Page" !!}</h1>
                            </div>
                            <div class="col-md-12">

                                @include('errors.session')

                                @section('content')
                                    <p>No content here </p>
                                @show

                            </div>
                        </div>
                        <!-- End Artikel -->
                    </div>
                    <!--End Content-->
                </section>
            </div>
        </div>
    </section>

    <!--Footer-->
    <section id="footer">
        <div class="footer-center">
            <div class="container">
                <div class="row">
                    <div class="column col-xs-12 col-sm-6 col-lg-3">
                        <div class="box contact-us">
                            <div class="box-heading">
                                <i class="fa fa-map-marker"></i><span><span> Contact</span> Us</span>
                            </div>
                            <p>
                                Kampus 3<br>
                                Jl. Prof. Dr. Soepomo, Janturan, Umbulharjo, Yogyakarta 55164
                            </p>
                        </div>
                    </div>
                                      
                    <div class="column col-xs-12 col-sm-6 col-lg-3">
                        <div class="box">
                            <div class="box-heading"><i class="fa fa-folder-open"></i><span> Kategori</span></div>
                            <ul class="list">
                                <li><a href="">Uncategory</a></li>
                                <li><a href="">Kampus</a></li>
                                <li><a href="">Berita</a></li>
                                <li><a href="">Pengumuman</a></li>
                            </ul>
                        </div>
                    </div>
                      
                    <div class="column col-xs-12 col-sm-6 col-lg-3">
                        <div class="box">
                        <div class="box-heading"><i class="fa fa-check"></i><span> Follow Us</span></div>
                        <div class="social">
                            <ul class="list">
                                <li><a href="#"><i class="fa fa-facebook"></i>Facebook</a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i>Twitter</a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i>GooglePlus</a> </li>
                            </ul>
                        </div>
                      </div>
                    </div>
                      
                    <div class="column col-xs-12 col-sm-6 col-lg-3">
                        <div class="box">
                            <div class="box-heading"><i class="fa fa-link"></i><span> Link Terkait</span></div>
                            <ul class="list">
                                <li>{!! link_to('http://tif.uad.ac.id', 'Teknik Informatika UAD') !!}</li>
                                <li>{!! link_to('http://fti.uad.ac.id', 'FTI UAD') !!}</li>
                                <li>{!! link_to('http://uad.ac.id', 'UAD') !!}</li>
                            </ul>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
        
        <div id="powered">
            <div class="container">
                <div class="copyright pull-left"> 
                    Copyright &copy 2015 {!! link_to('/', 'Portal Skripsi') !!}
                </div>
                <div class="copyright pull-right"> 
                    <a href="http://www.tif.uad.ac.id">Teknik Informatika</a>
                </div>
            </div>
        </div>
    </section>

    <!--Script-->
    @section('script')
    {!! HTML::script('js/jquery-1.9.1.min.js') !!}
    {!! HTML::script('js/bootstrap.js') !!}
    {!! HTML::script('js/jquery.min.js') !!}
    @show
    
</body>
</html>