app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/',         ['as' => 'home',            'uses' => 'HomeController@index']);
Route::get('login',     ['as' => 'login',           'uses' => 'LoginController@index']);
Route::post('login',    ['as' => 'login.submit',    'uses' => 'LoginController@submit']);
Route::get('logout',    ['as' => 'logout',          'uses' => 'LoginController@logout']);

Route::get('scan.php', 'DownloadController@getScan');
Route::controller('register', 'RegisterController');
Route::controller('panduan', 'PanduanController');
Route::controller('instruksi-kerja', 'InstruksiKerjaController');

Route::group(['namespace' => 'Backend', 'prefix' => 'backend', 'middleware' => ['auth', 'admin']], function()
{
    Route::get('/',                                         ['as' => 'backend',                             'uses' => 'HomeController@index']);
    Route::get('permintaan/active',                         ['as' => 'backend.permintaan.active',           'uses' => 'PermintaanController@active']);
    Route::get('permintaan/suspend',                        ['as' => 'backend.permintaan.showsuspend',      'uses' => 'PermintaanController@showSuspend']);
    Route::get('permintaan/{id}/activation',                ['as' => 'backend.permintaan.proccess',         'uses' => 'PermintaanController@proccess']);
    Route::get('permintaan/{id}/sendmail-activation',       ['as' => 'backend.permintaan.active.sendmail',  'uses' => 'PermintaanController@sendMailActivation']);
    Route::get('permintaan/{id}/destroy',                   ['as' => 'backend.permintaan.destroy.confirm',  'uses' => 'PermintaanController@destroyConfirm']);
    Route::get('permintaan/{id}/suspend',                   ['as' => 'backend.permintaan.suspend',          'uses' => 'PermintaanController@suspend']);
    Route::get('permintaan/{id}/unsuspend',                 ['as' => 'backend.permintaan.unsuspend',        'uses' => 'PermintaanController@unsuspend']);

    Route::resource('permintaan',                           'PermintaanController');

    Route::get('user/password/{id}',                        ['as' => 'backend.user.password',               'uses' => 'UserController@password']);
    Route::post('user/password/{id}',                       ['as' => 'backend.user.password.submit',        'uses' => 'UserController@change']);
    Route::resource('user', 'UserController');

    Route::get('upload',                                    ['as' => 'backend.upload.form',                 'uses' => 'UploadController@form']);
    Route::post('upload',                                   ['as' => 'backend.upload.submit',               'uses' => 'UploadController@submit']);

    Route::controller('laporan', 'LaporanController', [
        'getIndex'      => 'backend.laporan.index',
        'postDownload'  => 'backend.laporan.download',
    ]);

});

Route::group(['middleware' => 'auth.mahasiswa', 'namespace' => 'Mahasiswa'], function()
{
    Route::get('download/{dir?}',       ['as' => 'jurnal.show',     'uses' => 'JurnalController@show'])->where('dir', '([A-Za-z]+/?)+');
    Route::get('download-get/{dir?}',   ['as' => 'jurnal.download', 'uses' => 'JurnalController@download']);
});

Route::group(['prefix' => 'mahasiswa', 'namespace' => 'Mahasiswa'], function()
{
    Route::get('login',     ['as' => 'mahasiswa.login',           'uses' => 'LoginController@index']);
    Route::post('login',    ['as' => 'mahasiswa.login.submit',    'uses' => 'LoginController@submit']);

    Route::group(['middleware' => 'auth.mahasiswa'], function()
    {
        Route::get('logout',                ['as' => 'mahasiswa.logout',    'uses' => 'LoginController@logout']);
        Route::get('profile',               ['as' => 'mahasiswa.edit',      'uses' => 'UserController@edit']);
        Route::put('profile',               ['as' => 'mahasiswa.update',    'uses' => 'UserController@update']);
        Route::get('profile/password',      ['as' => 'mahasiswa.password',  'uses' => 'UserController@password']);
        Route::post('profile/password',     ['as' => 'mahasiswa.change',    'uses' => 'UserController@change']);
        Route::get('doc/{nim}',             ['as' => 'mahasiswa.doc',       'uses' => 'DocumentController@show']);
        Route::get('doc/{nim}/{filename}',  ['as' => 'mahasiswa.doc.pdf',   'uses' => 'DocumentController@pdf']);
    });
});


// Validator Extends

Validator::extend('kapasitas', function($attribute, $value, $parameters)
{
    return $value <= 50;
});

Validator::extend('old', function($attribute, $value, $parameters)
{
    $id     = $parameters[0];
    $user   = App\User::find($id);

    return Hash::check($value, $user->password);
});


Route::get('tesmail', function()
{
    $data['mahasiswa'] = App\Mahasiswa::first();

    Mail::send('emails.basic', $data, function($message)
    {
        $message->to('nurmanhabib@gmail.com', 'Habib Nurrahman')->subject('Coba Kirim Email');
    });
});

Route::get('quota', function()
{
    // $quota = new Nurmanhabib\QuotaTool\QuotaTool('/');
    // $quota->uid('habib');
    // $quota->limit(100024, 2000000);
    QuotaTool::filesystem('/');
    QuotaTool::uid('nurmanhabib')->limit('50G', '51G');

    echo QuotaTool::raw();

    echo '<hr>';

    echo QuotaTool::getLimit();
});

app/Profile.php
<?php namespace App;

class Profile extends Model {

	public function user()
    {
        return $this->belongsTo('User');
    }

    public function getFullNameAttribute()
    {
        return trim($this->first_name . ' ' . $this->last_name);
    }

}

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'email', 'password'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

	public static function boot()
	{
		parent::boot();

		User::creating(function($user)
		{
			$user->password = bcrypt($user->password);
		});
	}

	public function profile()
	{
		if ($this->level == 2)
			return $this->hasOne('App\Mahasiswa');
			return $this->hasOne('App\Profile');
	}

	public function isAdmin()
	{
		return in_array($this->attributes['level'], [0, 1]);
	}

	public function scopeOnlyUser($query)
	{
		return $query->select($this->getTable() . '.*')
		->rightJoin('profiles', 'profiles.user_id', '=', $this->getTable() . '.id');
	}

	public function scopeOnlyMahasiswa($query)
	{
		return $query->select($this->getTable() . '.*')
		->rightJoin('mahasiswa', 'mahasiswa.user_id', '=', $this->getTable() . '.id');
	}

	public function scopeName($query, $name)
	{
		return $query->where('name', $name);
	}

	public function scopeEmail($query, $email)
	{
		return $query->where('email', $email);
	}

	public function scopeNameOrEmail($query, $name, $email)
	{
		return $query->where('name', $name)->orWhere('email', $email);
	}

}

app/Http/Controllers/Backend/UserController.php
<?php namespace App\Http\Controllers\Backend;

use App\Http\Requests;

use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Http\Request;

use App\Http\Requests\UserRequest;
use App\User;
use App\Profile;
use App\Permintaan;

use Input;
use Hash;

use Navigator;

class UserController extends Controller {

	public function __construct()
	{
		parent::__construct();

        Navigator::setActive(route('backend.user.index'));
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(Authenticatable $user)
	{
		if ($user->level == 0) {
			$users = User::onlyUser()->paginate();

			return view('page.user.index')->with('page_title', 'User')->with('users', $users);
		} else {
			return $this->edit($user->id);
		}
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('page.user.create')->with('page_title', 'Create User');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(UserRequest $request)
	{
		$user = new User;
		$user->name		= $request->input('name');
		$user->email	= $request->input('email');
		$user->password	= $request->input('password');
		$user->status	= $request->input('status', 1);
		$user->level	= $request->has('level') ? $request->input('level', 1) : 1;
		$user->save();

		$profile	= new Profile;
		$profile->first_name	= $request->input('profile.first_name');
		$profile->last_name		= $request->input('profile.last_name');
		$profile->address		= $request->input('profile.address');
		$profile->phone_number	= $request->input('profile.phone_number');
		$profile->user_id		= $user->id;
		$profile->save();

		return redirect()->route('backend.user.edit', $user->id)->with('success', 'User berhasil dibuat');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$user = User::find($id);

		$profile = $user->profile;

		return view('page.user.edit')->with('user', $user)->with('profile', $profile)->with('page_title', 'Edit User');
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$user 		= User::find($id);
		$user->store();

		$profile	= Profile::find($user->profile->id);
		$profile->store(Input::get('profile'));

		return redirect()->route('backend.user.edit', $id)->with('success', 'User berhasil diperbarui');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id, Authenticatable $auth)
	{
		$user = User::find($id);

		Permintaan::migrateUser($user, $auth);

		$user->profile->delete();
		$user->delete();

		return redirect()->route('backend.user.index')->with('success', 'User berhasil dihapus');
	}

	public function password($id)
	{
		$user = User::find($id);

		return view('page.user.change_password', ['user' => $user]);
	}

	public function change(Requests\ChangePasswordRequest $request, $id)
	{
		$user 			= User::find($id);
		$user->password	= Hash::make($request->input('password'));
		$user->save();

		return redirect()->route('backend.user.edit', $id)->with('success', 'Password berhasil diperbarui');
	}

}

app/Http/Controllers/Mahasiswa/UserController.php
<?php namespace App\Http\Controllers\Mahasiswa;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

use Illuminate\Contracts\Auth\Authenticatable;

use App\Http\Requests\ChangePasswordRequest;

class UserController extends Controller {

	public function __construct(Authenticatable $user)
	{
		$this->user = $user;
	}

	public function edit()
	{
		$profile = $this->user->profile;
		$permintaan = $profile->permintaan;
		$skripsi = $profile->skripsi;

		if (!empty($permintaan)) {
			view()->share('permintaan', $permintaan);
			view()->share('skripsi', $skripsi);
		}

		return view('page.mahasiswa.edit')->withPageTitle('Profile')
		->withUser($this->user)
		->withProfile($this->user->profile);
	}

	public function update(Request $request)
	{
		$profile = $this->user->profile;
		$profile->store($request->input('profile'), ['email' => $request->input('email')]);

		$this->user->store($request->only('email'));

		return redirect()->route('mahasiswa.edit')->withSuccess('Profil berhasil diperbarui.');
	}

	public function password()
	{
		return view('page.mahasiswa.change_password')->withPageTitle('Change Password')
		->withUser($this->user);
	}

	public function change(ChangePasswordRequest $request)
	{
		return redirect()->route('mahasiswa.edit')->withSuccess('Password berhasil diperbarui.');
	}

}

resources/views/page/user/change_password.blade.php
@extends('layout.backend')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Change Password
            </div>

            {!! Form::open(['route' => ['backend.user.password', $user->id], 'class' => 'form-horizontal']) !!}
            {!! Form::hidden('id', $user->id) !!}
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            {!! Form::label('password', null, ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::password('password', ['class' => 'form-control']) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('password_confirmation', null, ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('password_old', null, ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::password('password_old', ['class' => 'form-control']) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="panel-footer">
                <button class="btn btn-primary"><i class="fa fa-fw fa-refresh"></i> Update</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/page/user/create.blade.php
@extends('layout.backend')

@section('content')
<div class="panel panel-default">
    {!! Form::open(['route' => 'backend.user.store', 'class' => 'form-horizontal']) !!}
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <legend>Informasi Login</legend>

                <div class="form-group">
                    {!! Form::label('name', 'Username', ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('name', null, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('password', null, ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        {!! Form::password('password', ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('password_confirmation', null, ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('email', null, ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('email', null, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <legend>Hak Akses</legend>

                <div class="form-group">
                    {!! Form::label('status', null, ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        {!! Form::select('status', ['Nonaktif', 'Aktif'], 1, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('level', 'Super Admin', ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        <div class="checkbox">
                            <label>
                                {!! Form::checkbox('level', 1) !!}
                            </label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <legend>Profile</legend>

                <div class="form-group">
                    {!! Form::label('profile[first_name]', 'Nama Depan', ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('profile[first_name]', null, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('profile[last_name]', 'Nama Belakang', ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('profile[last_name]', null, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('profile[address]', 'Address', ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('profile[address]', null, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('profile[phone_number]', 'Phone Number', ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('profile[phone_number]', null, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('profile[place_of_birth]', 'Tempat Lahir', ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('profile[place_of_birth]', null, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('profile[date_of_birth]', 'Tanggal Lahir', ['class' => 'control-label col-sm-4']) !!}
                    <div class="col-sm-8">
                        {!! Form::text('profile[date_of_birth]', null, ['class' => 'form-control']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel-footer">
        <button class="btn btn-primary">Create</button>
    </div>
    {!! Form::close() !!}
</div>
@endsection

resources/views/page/user/edit.blade.php
@extends('layout.backend')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Informasi
            </div>

            {!! Form::model($user, ['route' => ['backend.user.update', $user->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            {!! Form::label('name', 'Username', ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::text('name', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('password', null, ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <a href="{!! route('backend.user.password', $user->id) !!}" class="btn btn-primary">Change password</a>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('email', null, ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::text('email', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('status', null, ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::select('status', ['Nonaktif', 'Aktif'], null, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            {!! Form::label('profile[first_name]', 'Nama Depan', ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::text('profile[first_name]', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('profile[last_name]', 'Nama Belakang', ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::text('profile[last_name]', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('profile[address]', 'Address', ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::text('profile[address]', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('profile[phone_number]', 'Phone Number', ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::text('profile[phone_number]', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>
    
                        <div class="form-group">
                            {!! Form::label('profile[place_of_birth]', 'Tempat Lahir', ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::text('profile[place_of_birth]', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('profile[date_of_birth]', 'Tanggal Lahir', ['class' => 'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                {!! Form::text('profile[date_of_birth]', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel-footer">
                <button class="btn btn-primary">Update</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/page/user/index.blade.php
@extends('layout.backend')

@section('style')
@parent
    <style>
    table a.btn {
        float: left;
        margin-right: 5px;
    }
    </style>
@endsection

@section('content')
<a href="{!! route('backend.user.create') !!}" class="btn btn-primary">Create</a>

<hr>

<table class="table table-hover table-hover table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Nama</th>
            <th>Username</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @forelse($users as $user)
        <tr>
            <td>{!! $user->id !!}</td>
            <td>{!! $user->profile ? $user->profile->full_name : '' !!}</td>
            <td>{!! $user->name !!}</td>
            <td>{!! $user->email !!}</td>
            <td><a href="{!! route('backend.user.edit', $user->id) !!}" class="btn btn-success btn-xs"><i class="fa fa-fw fa-pencil"></i></a> {!! Form::open(['route' => ['backend.user.destroy', $user->id], 'method' => 'DELETE']) !!}<button href="{!! url() !!}" class="btn btn-danger btn-xs btn-delete"><i class="fa fa-fw fa-trash-o"></i></button>{!! Form::close() !!}</td>
        </tr>
        @empty
        <tr>
            <td colspan="5">Tidak ada data</td>
        </tr>
        @endforelse
    </tbody>
</table>
@endsection